### ISSUE TITLE
Parameter case sensitivity

### ISSUE THREAD

**Issue by rmckeel** [formio/formio-php#2]
Hello,

  I am trying out this library.  Works as I'd expect, with one exception thus far.  The field "X-Jwt-Token" seems to be case sensitive.  That is, checking `$response['headers']['x-jwt-token']` does not work, whereas checking `$response['headers']['X-Jwt-Token']` does work.

  In my code, I have made all uses of that `X-Jwt-Token`.  I'd recommend that update.  I created a [PR](https://github.com/formio/formio-php/pull/1) if that's easy to integrate and this change makes sense to you.

Thanks!

  Ryan

**Comment by travist** [comment]
Thanks @rmckeel. I responded to the PR. Please let me know if my proposal would fit your needs.

**Comment by rmckeel** [comment]
@travist Just wanted to mention, I did respond to the PR.  Let me know what you think about the possibility of additional formatting / PHP documentation in that file as a new PR.

**Comment by travist** [comment]
@rmckeel sorry about that. I was waiting for an update to the PR to accept it. If you don't mind, would you make that change and then submit an update to the PR? That way I don't have to go through the trouble of pulling in your branch, making the change, and then testing it on my end. Since you already seem to have a test case, it would be much easier on me if you would make the change to the existing PR. I will then pull it in.

**Comment by rmckeel** [comment]
@travist Makes sense, I'll see what I can do there for the new PR in the next few days.  Thanks!

**Comment by rmckeel** [comment]
@travist I made a 'minimal change' PR that should work to fix the problem, but not adjust code style / etc.  If you're interested in our code style / consistency / commenting updates, let me know and I can make another PR.  No worries if you're not interested.

I'll close since PR can stand on its own.

Thanks!
